require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 20
