# Theme settings
title: GitHub Pages LilyPond template
short_title: Test
description: >-
  Template used for LilyPond projects on GitHub Pages.
baseurl: ""
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-jekyll-template
lang: en-US
show_downloads: false
copyright: false
# Jekyll settings
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "a3"
    values:
      a3: true
  - scope:
      path: "tabloid"
    values:
      tabloid: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
  - scope:
      path: "video"
    values:
      video: true
