# Theme settings
title: GitHub Pages LilyPond template
short_title: ""
description: >-
  Template used for LilyPond projects on GitHub Pages.
baseurl: ""
url: https://alexis.jeandeau.fr
repository: jeandeaual/lilypond-jekyll-template
lang: en-US
root_repo_path: /partitions
copyright: false
# Jekyll settings
include:
  - .nojekyll
exclude:
  - config.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - spec
  - .rspec
  - .rubocop.yml
  - .solargraph.yml
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
  - .github/
  - .vscode/
plugins:
  - jekyll-github-metadata
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-timeago
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "a3"
    values:
      a3: true
  - scope:
      path: "tabloid"
    values:
      tabloid: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
  - scope:
      path: "video"
    values:
      video: true
jekyll-minifier:
  remove_intertag_spaces: true
