title: GitHub Pages LilyPond template
description: >-
  Template used for LilyPond projects on GitHub Pages.
baseurl: ""
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-jekyll-template
lang: en-US
show_downloads: false

# Build settings
theme: jekyll-theme-minimal
plugins: []

defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
