name: build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.github/workflows/lint.yml'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.github/workflows/lint.yml'
      - '.github/workflows/test.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install the dependencies
        run: |
          bundle config set without 'development'
          bundle install --jobs 4 --retry 3
      - name: Build the Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
